[versions]
agp = "9.0.0-beta05"
desugar_jdk_libs = "2.1.5"
playServicesWearable = "19.0.0"
kotlin = "2.2.21"
composeBom = "2025.12.00"
dependencyAnalysis = "3.5.1"
remoteCompose = "1.0.0-SNAPSHOT"
runtime = "1.10.0"
uiTooling = "1.10.0"
wear = "1.0.0-SNAPSHOT"
wearCore = "1.0.0-SNAPSHOT"
wearToolingPreview = "1.0.0"
composeMaterial = "1.5.6"

[libraries]
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiTooling" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
remote-creation-compose = { module = "androidx.compose.remote:remote-creation-compose", version.ref = "remoteCompose" }
runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "uiTooling" }
wear = { module = "androidx.glance.wear:wear", version.ref = "wear" }
wear-core = { module = "androidx.glance.wear:wear-core", version.ref = "wearCore" }
wear-tooling-preview = { module = "androidx.wear:wear-tooling-preview", version.ref = "wearToolingPreview" }
wear-compose-ui-tooling = { module = "androidx.wear.compose:compose-ui-tooling", version.ref = "composeMaterial" }
remote-tooling-preview = { module = "androidx.compose.remote:remote-tooling-preview", version.ref = "remoteCompose" }
remote-material3 = { module = "androidx.wear.compose.remote:remote-material3", version.ref = "remoteCompose" }
remote-core = { module = "androidx.compose.remote:remote-core", version.ref = "remoteCompose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }

